name: Deploy to VPS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AIOGRAM_BOT_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.AIOGRAM_BOT_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AIOGRAM_BOT_SSH_HOST }}
          username: ${{ secrets.AIOGRAM_BOT_SSH_USER }}
          key: ${{ secrets.AIOGRAM_BOT_SSH_PRIVATE_KEY }}
          script: |
            echo '--- START WORK ON REMOTE SERVER ---';
            cd LariskaBot;
            echo '--- EXPORT VARIABLES ---';
            export BOT_TOKEN=${{ secrets.AIOGRAM_BOT_TOKEN }};
            export AI_KEY=${{ secrets.LARISKA_AI_KEY }};
            export ADMINS=${{ vars.ADMINS }}
            echo '--- LIST OF FILES ---';
            ls -al;
            echo '--- GIT PULL ---'
            git pull;
            echo '--- DOCKER OPERATIONS ---';
            docker-compose down;
            docker rmi AIOGRAM_BOT;
            echo '--- LIST OF DOCKER CONTAINERS ---';
            docker ps -a;
            echo '--- UP CONTAINER ---';
            docker-compose up -d;
            echo '--- LIST OF DOCKER CONTAINERS ---';
            docker ps -a;
